"""create_omr_and_grades_tables

Revision ID: 8c7e7c2e4e00
Revises: 0001_create_users
Create Date: 2026-07-20 16:19:46.427573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7e7c2e4e00'
down_revision: Union[str, None] = '0001_create_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omr_templates',
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('layout_version', sa.String(length=50), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('options_per_question', sa.Integer(), server_default='5', nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('ONLINE', 'OMR', name='grade_source_type', native_enum=False), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('omr_scans',
    sa.Column('omr_template_id', sa.UUID(), nullable=False),
    sa.Column('student_code', sa.String(length=5), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'SUCCESS', 'REVIEW_NEEDED', 'FAILED', name='omr_scan_status', native_enum=False), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('detected_answers', sa.JSON(), nullable=True),
    sa.Column('raw_confidence', sa.JSON(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['omr_template_id'], ['omr_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('student_code', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_users_student_code'), 'users', ['student_code'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='user_role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='user_role', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_student_code'), table_name='users')
    op.drop_column('users', 'student_code')
    op.drop_column('users', 'is_active')
    op.drop_table('omr_scans')
    op.drop_table('grades')
    op.drop_table('omr_templates')
    # ### end Alembic commands ###
